spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdb
    username: root
    password: A123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
